### ISSUE TITLE
Ping stale ACK reviewers?

### ISSUE THREAD

**Issue by aureleoules** [MarcoFalke/DrahtBot#11]
Would it be reasonable to ping reviewers if they left an ACK that became stale after a push?

**Comment by fanquake** [comment]
Depends on how it's done. It can't be in the form of the bot just posting more comments, as that's just spam, for maintainers, and repo subscribers. Reviewers may already have been requested for review, and we don't want to bombard people with duplicate notifications every-time someone pushes to a branch.

**Comment by MarcoFalke** [comment]
Yeah, I think GitHub already sends a notification on a `git push`. Also, there will be comments/replies indicating a push in most cases, no?

**Comment by aureleoules** [comment]
Yes, I understand that comments would spam a bit. A solution would have been to ping the reviewers in the summary comment by editing it but it doesn't ping.

> Yeah, I think GitHub already sends a notification on a git push. Also, there will be comments/replies indicating a push in most cases, no?

Yes, but sometimes, at least I do :clown_face:, forget that I've reviewed the PR in question.
By email? That's a bit aggressive :grimacing:

**Comment by ajtowns** [comment]
I think you could use the ["request review"](https://docs.github.com/en/rest/pulls/review-requests) feature for this? 

```sh
$ curl -i -X POST -u DrahtBot https://api.github.com/repos/bitcoin/bitcoin/pulls/26525/requested_reviewers -d '{"reviewers":["ajtowns"]}'
$ curl -i -X DELETE -u DrahtBot https://api.github.com/repos/bitcoin/bitcoin/pulls/26525/requested_reviewers -d '{"reviewers":["ajtowns"]}'
```

Maybe only do it when the last push was a few days ago?

**Comment by aureleoules** [comment]
> I think you could use the ["request review"](https://docs.github.com/en/rest/pulls/review-requests) feature for this?

I agree this is a good idea.

> Maybe only do it when the last push was a few days ago?

I think it would also be useful to request reviewers after every new push as the GitHub notification will be `review requested` and the user can prioritize pulls to review based on this maybe?

**Comment by aureleoules** [comment]
> I think you could use the ["request review"](https://docs.github.com/en/rest/pulls/review-requests) feature for this?

I agree this is a good idea.

> Maybe only do it when the last push was a few days ago?

I think it would also be useful to request reviewers after every new push as the GitHub notification will be `review requested` and the user can prioritize pulls to review based on this maybe?

**Comment by MarcoFalke** [comment]
We could also request review from anyone else that did any kind of ACK?

**Comment by aureleoules** [comment]
> I think this should be an async approach, I agree that pinging in ~real-time is unproductive here. An alternative approach: have an overview of stale ACKs (grouped by user) on a separate page (e.g. a github gist) where people who are interested (e.g. I would find it helpful to see where I have stale ACKs) can periodically go to figure out what they want to work on, without anyone getting spammed?

achow101 just built something similar: https://github.com/achow101/ackboard.

**Comment by MarcoFalke** [comment]
Did something in 0a9955b46b0a7f9277628094df28fb12f2cdffb1
