### ISSUE TITLE
Incorrect concept NACK

### ISSUE THREAD

**Issue by fanquake** [MarcoFalke/DrahtBot#16]
comment here: https://github.com/bitcoin/bitcoin/pull/26076#issuecomment-1294093144

which is explicitly "not a NACK", is listed as a "concept NACK" in the summary comment.

**Comment by MarcoFalke** [comment]
It will never be possible to get 100% accuracy, unless you force everyone to use an exact format. I guess this instance should have been parsed as "approach nack"?

Either way, it can simply be ignored for the merge, or it will be updated on a fresh review, whichever happens earlier.

**Comment by MarcoFalke** [comment]
Same here https://github.com/bitcoin/bitcoin/pull/26514#pullrequestreview-1187122628

**Comment by stickies-v** [comment]
Perhaps people will start to use (N)ACK more sparingly in their comments when they know DrahtBot is parsing it - and I think that's not a bad thing. Also for that reason, I think it's important we keep the parsing rules simple, so people can better anticipate how their comments will be interpreted.

And of course, DrahtBot is just a tool and we must never rely on just this parsed overview, so a couple of wrong interpretations here and there aren't a concern to me.

**Comment by Sjors** [comment]
Maybe folks should use nNACK :-)

**Comment by 0xB10C** [comment]
https://github.com/bitcoin/bitcoin/pull/26525#issuecomment-1324400724 is counted as NACK (it's an ACK)

**Comment by MarcoFalke** [comment]
Maybe there should be an "inconclusive" review if multiple review types are found?

**Comment by aureleoules** [comment]
> [bitcoin/bitcoin#26525 (comment)](https://github.com/bitcoin/bitcoin/pull/26525#issuecomment-1324400724) is counted as NACK (it's an ACK)

This one can probably get fixed by prioritizing `ACK <hash>` before `NACK` simply by moving the `NACK` regex below the `ACK <hash>` one.
But this may not work for all cases?

**Comment by 0xB10C** [comment]
> > [bitcoin/bitcoin#26525 (comment)](https://github.com/bitcoin/bitcoin/pull/26525#issuecomment-1324400724) is counted as NACK (it's an ACK)
> 
> This one can probably get fixed by prioritizing `ACK <hash>` before `NACK` simply by moving the `NACK` regex below the `ACK <hash>` one.
> But this may not work for all cases?
> 

I think it could work. I guess people don't add the commit hash to a retracted ACK like:


I retract my ACK 7374727. I'm now NACK.

**Comment by 0xB10C** [comment]
Some reddit bots mention to report incorrect bot behavior. Either via a link to an external site or by down voting the bot. Could be done with the 👎 reaction as in https://github.com/bitcoin/bitcoin/pull/26514#issuecomment-1320972323. I assume it's possible to get reactions to DrahtBot comments and list downvoted ones somewhere?

**Comment by aureleoules** [comment]
That's a good idea. For the moment Drahtbot could just remove the review of the user from the summary comment if the user reacts with thumbs down? This behavior should also be explained in the summary comment.

**Comment by michaelfolkson** [comment]
DrahtBot gone full sentient AI with its thumbs down on @0xB10C comment

**Comment by vostrnad** [comment]
Also quoted text should be ignored: https://github.com/bitcoin/bitcoin/pull/26525#issuecomment-1326756947

**Comment by MarcoFalke** [comment]
It should be ignored via `    let lines = comment.split('\n').filter(|s| !s.starts_with('>'));`

Not sure why it doesn't.

**Comment by MarcoFalke** [comment]
Ah, probably because f361fb03c641a88fa5c325f6ef692e8ae405e40a does not preserve the raw text
