### ISSUE TITLE
Doesn't register non-upper-case ACKs

### ISSUE THREAD

**Issue by willcl-ark** [MarcoFalke/DrahtBot#23]
Not sure if this would cause unintended side-effects, but my "Ack" here was missed:

https://github.com/bitcoin/bitcoin/pull/26257#pullrequestreview-1172862157

**Comment by MarcoFalke** [comment]
See also:

* https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#code-review
* https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/78ab16ae88af7a5ef886ae8cef6df2e9ef3f6085/github-merge.py#L214

**Comment by willcl-ark** [comment]
Good point(s)!

**Comment by 0xB10C** [comment]
@willcl-ark at it again with the lowercase acks. This https://github.com/bitcoin/bitcoin/pull/27559#issuecomment-1532773174 is not picked up by @DrahtBot.
