### ISSUE TITLE
Concept ACK?

### ISSUE THREAD

**Issue by fanquake** [MarcoFalke/DrahtBot#26]
Did Drahtbot imagine a concept ACK here: https://github.com/bitcoin/bitcoin/pull/26795#issuecomment-1369167875? I can't see where it's come from in the comments.

**Comment by aureleoules** [comment]
Might have been this line:
```diff
+        dump_dir = '/tmp/temp_git/' ##HACK
```

**Comment by MarcoFalke** [comment]
Yes, bugs are expected, see https://github.com/MarcoFalke/DrahtBot/issues/16#issuecomment-1324251484
