### ISSUE TITLE
Remove "Count" in ACK tracker

### ISSUE THREAD

**Issue by stickies-v** [MarcoFalke/DrahtBot#8]
I think the "Count" column should be removed from the ACK tracker. It's a meaningless metric because it does in no way capture the review quality, and it can give off the false impression that PRs are merged based on a simple (N)ACK count. 

The main benefit for me of this tracker is to quickly see where everyone currently stands, and to have links to their comments (especially helpful in older PRs with lots of comment history).

**Comment by MarcoFalke** [comment]
sgtm
